### PR TITLE
Chore: Bump pyroscope-go/godeltaprof to v0.1.8 to fix panic on go 1.23

### PR DESCRIPTION
**Pull request by Antiz96**
See https://github.com/grafana/pyroscope-go/issues/118

Fixes https://github.com/grafana/grafana-zabbix/issues/1874

### CODE REVIEW

**Comment by ivanahuckova** [comment]
@Antiz96 thank you for your contribution. We appreciate it. It looks that in the meantime, we fixed this by https://github.com/grafana/grafana-zabbix/pull/1877/files. So closing this. But again, thank you. :)

**Comment by Antiz96** [comment]
Alright, that's fine thanks! :)

Do you know if a new release including this fix is planned soon? 
I'm the package maintainer for the grafana-zabbix Arch Linux package, so it's just to know if I can expect a new release I'll be able to build as-is or if I should backport those fixes into our current package (Arch is already on go 1.23).

**Comment by ivanahuckova** [comment]
We can release next week, is that all right?

**Comment by Antiz96** [comment]
Sure that'll do. Thanks again!

**Comment by Antiz96** [comment]
> New version of Zabbix v4.5.4 has been released.

Alright! I can't see the tag yet but I assume that's coming :smile: 
Thanks a lot!

**Comment by Antiz96** [comment]
Thanks again :tada:

**Pull request closed without merging**
