### PR TITLE
Docs: rename image paths

### LINKED ISSUE #1773: Images in Docs are not shown
**Describe the bug**
Images on the Grafana-Zabbix Plugin Docs are not shown because the docs have moved.

**Expected behavior**
The pictures should be shown.

**Screenshots**
Screenshot 2024-01-11 093047

### PR DESCRIPTION
**Pull request by rafaeldaetwyler**
Fixes #1773

### CODE REVIEW

**Comment by zoltanbedi** [comment]
Thanks for creating a PR @rafaeldaetwyler can you please sign the CLA so I can merge this?

**Comment by rafaeldaetwyler** [comment]
@zoltanbedi I signed it now, seems like the check is still pending though.

**Comment by zoltanbedi** [comment]
@rafaeldaetwyler it looks like the commit is not made by your GitHub user.

**Comment by rafaeldaetwyler** [comment]
@zoltanbedi Thanks for the pointer. I added the email-address, now you should be able to merge it.

**Review by zoltanbedi — APPROVED** [review]

**Comment by zoltanbedi** [comment]
Thank you! @rafaeldaetwyler

**Pull request merged**
