### PR TITLE
Parallel query handling

### PR DESCRIPTION
**Pull request by iqbalaydrus**
Solves #1746

### CODE REVIEW

**Comment by zoltanbedi** [comment]
Hi @iqbalaydrus,
thanks for opening this PR, we are going to take a look at it soon. In the meantime can you please add tests for this?

**Comment by iqbalaydrus** [comment]
I'm not quite sure what tests I should add for parallelization, do you have any suggestions?

**Comment by iqbalaydrus** [comment]
Well parallization just makes things faster without changing any of the app behaviour. So as long as the current tests cover my changes it should be good. But I don't think the tests touch the `QueryData` method yet. I'll take a look later whether it's possible to add tests to that.

**Comment by ivanahuckova** [comment]
Hi @iqbalaydrus, thank you for contribution. We have decided that currently we don't want to support parallel query handling because of increased complexity. We will keep the issue open in case we revisit this decision later.

**Comment by xiaohuait** [comment]
I also encountered this problem. When I was using Zabbix to create a network architecture diagram and queried 28 pieces of data, the response time reached 16 seconds, which was a very poor experience.

**Pull request closed without merging**
